name: eatopia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cloud_firestore: ^5.6.0
  email_validator: ^3.0.0
  firebase_core: ^3.9.0
  flutter_signin_button: ^2.0.0
  flutter:
    sdk: flutter
  flutter_awesome_buttons: ^1.1.0
  flutter_spinkit: ^5.1.0
  google_maps_flutter: ^2.2.5
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  search_map_place_updated: ^0.0.4
  firebase_auth: ^5.3.4
  google_sign_in: ^6.1.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7
  flutter_launcher_icons: ^0.14.2
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3
  shimmer_animation: ^2.1.0+1
  uuid: ^4.5.1
  geocoding: ^3.0.0
  path: ^1.9.0
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  image_path: "images/logo.png" 
  android: true

flutter:
  uses-material-design: true

  fonts:
  - family: Ubuntu
    fonts:
    - asset: fonts/Ubuntu/Ubuntu-Light.ttf
  - family: Ubuntu-bold
    fonts:
    - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
  assets:
    - images/




