// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrEejAmvE_v5aX4a5NdKWU9W7NTh8r5Qc',
    appId: '1:562134379208:android:ad84e9e6b1d249684f93fd',
    messagingSenderId: '562134379208',
    projectId: 'doanchuyennganh-65edf',
    storageBucket: 'doanchuyennganh-65edf.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPNq7kboTi9OdOAM6GTzVw2KOlhqzQTNM',
    appId: '1:562134379208:web:70f118acdff9dc514f93fd',
    messagingSenderId: '562134379208',
    projectId: 'doanchuyennganh-65edf',
    authDomain: 'doanchuyennganh-65edf.firebaseapp.com',
    storageBucket: 'doanchuyennganh-65edf.firebasestorage.app',
    measurementId: 'G-5W15382LYH',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPNq7kboTi9OdOAM6GTzVw2KOlhqzQTNM',
    appId: '1:562134379208:web:c6004e52c8c571aa4f93fd',
    messagingSenderId: '562134379208',
    projectId: 'doanchuyennganh-65edf',
    authDomain: 'doanchuyennganh-65edf.firebaseapp.com',
    storageBucket: 'doanchuyennganh-65edf.firebasestorage.app',
    measurementId: 'G-WH1Y0C3C0W',
  );

}